/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('./components/B/Alert.vue')['default']
    BAvatar: typeof import('./components/B/Avatar.vue')['default']
    BAvatarGroup: typeof import('./components/B/AvatarGroup.vue')['default']
    BBadge: typeof import('./components/B/Badge.vue')['default']
    BBreadcrumb: typeof import('./components/B/Breadcrumb.vue')['default']
    BBreadcrumbItem: typeof import('./components/B/BreadcrumbItem.vue')['default']
    BBreadcrumbLink: typeof import('./components/B/BreadcrumbLink.vue')['default']
    BButton: typeof import('./components/B/Button.vue')['default']
    BButtonClose: typeof import('./components/B/ButtonClose.vue')['default']
    BButtonGroup: typeof import('./components/B/ButtonGroup.vue')['default']
    BButtonToolbar: typeof import('./components/B/ButtonToolbar.vue')['default']
    BCard: typeof import('./components/B/Card.vue')['default']
    BCardBody: typeof import('./components/B/CardBody.vue')['default']
    BCardFooter: typeof import('./components/B/CardFooter.vue')['default']
    BCardGroup: typeof import('./components/B/CardGroup.vue')['default']
    BCardHeader: typeof import('./components/B/CardHeader.vue')['default']
    BCardImage: typeof import('./components/B/CardImage.vue')['default']
    BCardImageLazy: typeof import('./components/B/CardImageLazy.vue')['default']
    BCardImg: typeof import('./components/B/CardImg.vue')['default']
    BCardImgLazy: typeof import('./components/B/CardImgLazy.vue')['default']
    BCardSubtitle: typeof import('./components/B/CardSubtitle.vue')['default']
    BCardSubTitle: typeof import('./components/B/CardSubTitle.vue')['default']
    BCardText: typeof import('./components/B/CardText.vue')['default']
    BCardTitle: typeof import('./components/B/CardTitle.vue')['default']
    BImg: typeof import('./components/B/Img.vue')['default']
    BImgLazy: typeof import('./components/B/ImgLazy.vue')['default']
    BLink: typeof import('./components/B/Link.vue')['default']
    BRow: typeof import('./components/B/Row.vue')['default']
    BVTransition: typeof import('./components/B/VTransition.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    LayoutFooter: typeof import('./components/Layout/Footer.vue')['default']
    LayoutHeader: typeof import('./components/Layout/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
